### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by BrianMitchL**
- Update dependencies
- Use Node 16 for running action
- Set TypeScript and `@vercel/ncc` targets to es2021

### CODE REVIEW

**Review by ryanmr — APPROVED** [review]
Legendary update!

**Comment by ryanmr** [comment]
The response gif is a bit obscure 😆

**Review by ryanmr — APPROVED** [review]
This update is perfect, just like spaghetti.

**Comment by ryanmr** [comment]
Ok, this one was better 👍👍👍

**Review by ryanmr — APPROVED** [review]
3 thumbs up, looks good to me. 👍👍👍

**Comment by ryanmr** [comment]
Excellent, indeed

**Comment by BrianMitchL** [comment]
Thanks for the amazing reviews @ryanmr!

**Pull request merged**
